# Generated by Django 2.2.2 on 2019-06-21 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odpowiedz', models.CharField(choices=[('tak', 'TAK'), ('nie', 'NIE')], max_length=3)),
                ('licznik', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Odp2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odps2', models.CharField(choices=[('tak', 'TAK'), ('nie', 'NIE')], max_length=3)),
                ('licznik', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pytanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('tresc', models.TextField(blank=True)),
                ('grupa', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Wybory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_pytania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestO.Pytanie')),
                ('wybor_odp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestO.Odp')),
            ],
        ),
        migrations.AddField(
            model_name='odp',
            name='pyt_odp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestO.Pytanie'),
        ),
    ]
