# Generated by Django 2.2.2 on 2019-06-21 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odp2',
            name='odps2',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1),
        ),
        migrations.AlterField(
            model_name='wybory',
            name='wybor_odp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestO.Odp2'),
        ),
        migrations.DeleteModel(
            name='Odp',
        ),
    ]
